require 'inifile'
require 'date'

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.guest = "windows"
  config.vm.boot_timeout = 600

  config.vm.provider :aws do |aws, override|
    # https://gist.github.com/amosshapira/e043ef116bfdfe92e3cd
    aws_credentials = IniFile.load(File.expand_path('~/.aws/credentials'))
    aws.access_key_id = aws_credentials['default']['aws_access_key_id']
    aws.session_token = aws_credentials['default']['aws_session_token']
    aws.secret_access_key = aws_credentials['default']['aws_secret_access_key']

    aws.region = 'us-west-2'

    aws.keypair_name = "my-keyfilename" # << FIXME
    aws.ami = "ami-6115e519" # Microsoft Windows Server 2008 Base Micro us-west-2
    aws.instance_type = "t1.micro"
    aws.terminate_on_shutdown = true
    aws.security_groups = "sg-12345" # << FIXME
    aws.subnet_id = "subnet-12345" # << FIXME
    aws.associate_public_ip = true

    # aws.spot_instance = true
    # aws.spot_max_price = 0.0155
    # aws.spot_valid_until = DateTime.now + (3.0/24)
    aws.tags = {
      'Name' => 'vagrant-test'
    }

    aws.user_data = File.read("user_data2.txt")

    override.vm.communicator = "winrm"
    override.winrm.username = "Administrator"
    override.winrm.password = “<insert password here>“


    override.vm.synced_folder ".", "/vagrant", disabled: true
  end
end